name: Build and test

on:
  pull_request:
  workflow_call:
    inputs:
      upload-artifact:
        default: false
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0 # Fetch entire history, because the check_links.rb script relies on it

    - name: Set up Ruby
      uses: ruby/setup-ruby@22fdc77bf4148f810455b226c90fb81b5cbc00a7 # v1.171.0
      with:
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: '12'

    - name: Build
      run: bundle exec middleman build
    
#    - name: Check external links
#      if: ${{ github.ref != 'refs/heads/main' }}
#      run: bundle exec ruby check_links.rb

    # Share data between the build and deploy jobs so we don't need to run `npm run build` again on deploy
    # Upload the deploy folder as an artifact so it can be downloaded and used in the deploy job
    - name: Upload artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.1.3
      if: ${{ inputs.upload-artifact }}
      with:
          name: build
          path: build/**
          retention-days: 1
